spring:
  application:
    name: testapigraph      

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}


instagram:
  access-token: ${INSTAGRAM_ACCESS_TOKEN}
  account-id: ${INSTAGRAM_ACCOUNT_ID}

facebook:
  access-token: ${FACEBOOK_ACCESS_TOKEN}
  page-id: ${FACEBOOK_PAGE_ID}
  
#file:
#  dir: src/main/resources/uploads 

